# Generated by Django 5.1.2 on 2024-11-24 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_contractorusermodel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorPublicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='accounts.contractorusermodel')),
            ],
        ),
    ]
