# Generated by Django 5.1.2 on 2024-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorpublicmodel',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
