# Generated by Django 5.1.2 on 2024-11-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorpublicmodel',
            options={'ordering': ('contractor', 'slug')},
        ),
    ]
