# Generated by Django 5.1.2 on 2024-12-01 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_clientfeedbackmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedbackmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientfeedbackmodel',
            name='client_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
