# Generated by Django 5.1.2 on 2024-12-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_clientfeedbackmodel_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfeedbackmodel',
            name='updated_at',
        ),
    ]
