# Generated by Django 5.1.2 on 2024-12-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_contractor_clientfeedbackmodel_public_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedbackmodel',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
