# Generated by Django 5.1.2 on 2024-12-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_clientfeedbackmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedbackmodel',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
