# Generated by Django 5.1.2 on 2024-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_clientfeedbackmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedbackmodel',
            name='comment',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
