# Generated by Django 5.1.2 on 2024-12-10 22:36

import maistorbox.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorusermodel',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[maistorbox.accounts.validators.PhoneNumberValidator(5)]),
        ),
        migrations.AlterField(
            model_name='contractorusermodel',
            name='profile_image',
            field=models.ImageField(upload_to='contractor-users-profile-pictures', validators=[maistorbox.accounts.validators.ImageSizeValidator(10)]),
        ),
    ]
