# Generated by Django 5.1.2 on 2024-11-04 18:42

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUserModel',
            fields=[
                ('baseusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.baseusermodel',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='contractoruser',
            name='profile_picture',
            field=models.ImageField(upload_to='media/media'),
        ),
        migrations.AlterField(
            model_name='contractoruser',
            name='regions',
            field=models.ManyToManyField(blank=True, to='accounts.regions'),
        ),
        migrations.AlterField(
            model_name='contractoruser',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='accounts.specializations'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_images'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='specializations',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
