# Generated by Django 5.1.2 on 2024-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoruser',
            name='profile_picture',
            field=models.ImageField(upload_to='media/media'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='media/user_images'),
        ),
    ]
