# Generated by Django 5.1.2 on 2024-12-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractorProject',
            new_name='ContractorProjectModel',
        ),
    ]
