# Generated by Django 5.1.2 on 2024-11-05 06:30

from django.db import migrations


from django.db import migrations

from maistorbox.accounts.choices import ContractorRegions


def populate_initial_data(apps, schema_editor):
    Specializations = apps.get_model('accounts', 'Specializations')
    Regions = apps.get_model('accounts', 'Regions')

    specializations_data = [
        "",
    ]
    for name in specializations_data:
        Specializations.objects.create(name=name)

    regions_data = [
        ContractorRegions
    ]
    for name in regions_data:
        Regions.objects.create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_regularusermodel_and_more'),
    ]

    operations = [
    ]
