# Generated by Django 5.1.2 on 2024-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_regions_specializations_contractorusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorusermodel',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contractorusermodel',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contractorusermodel',
            name='profile_image',
            field=models.ImageField(upload_to='media/contractor-users-profile-pictures'),
        ),
        migrations.AlterField(
            model_name='contractorusermodel',
            name='regions',
            field=models.ManyToManyField(related_name='users', to='accounts.regions'),
        ),
        migrations.AlterField(
            model_name='contractorusermodel',
            name='specializations',
            field=models.ManyToManyField(related_name='users', to='accounts.specializations'),
        ),
    ]
