# Generated by Django 5.1.2 on 2024-12-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_contractorproject_contractorprojectmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specializations',
            new_name='Region',
        ),
        migrations.RenameModel(
            old_name='Regions',
            new_name='Specialization',
        ),
    ]
