# Generated by Django 5.1.2 on 2024-11-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='regions',
            field=models.CharField(blank=True, choices=[('Sofia Grad', 'София град'), ('Plovdiv', 'Пловдив'), ('Varna', 'Варна'), ('Burgas', 'Бургас'), ('Stara Zagora', 'Стара Загора'), ('Blagoevgrad', 'Благоевград'), ('Pazardzhik', 'Пазарджик'), ('Sofia Oblast', 'София-област'), ('Pleven', 'Плевен'), ('Veliko Tarnovo', 'Велико Търново'), ('Haskovo', 'Хасково'), ('Ruse', 'Русе'), ('Sliven', 'Сливен'), ('Shumen', 'Шумен'), ('Dobrich', 'Добрич'), ('Kardzhali', 'Кърджали'), ('Vratsa', 'Враца'), ('Montana', 'Монтана'), ('Lovech', 'Ловеч'), ('Pernik', 'Перник'), ('Yambol', 'Ямбол'), ('Kyustendil', 'Кюстендил'), ('Targovishte', 'Търговище'), ('Razgrad', 'Разград'), ('Silistra', 'Силистра'), ('Gabrovo', 'Габрово'), ('Smolyan', 'Смолян'), ('Vidin', 'Видин')], max_length=50),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='specializations',
            field=models.CharField(blank=True, choices=[('general_contractors', 'Главни изпълнители'), ('excavation', 'Изкопни работи'), ('concrete', 'Бетон'), ('framing', 'Рамкиране'), ('steel', 'Стомана'), ('window_and_door', 'Прозорци и врати'), ('electrical', 'Електрически'), ('plumbing', 'ВиК'), ('hvac', 'Отопление, вентилация и климатизация'), ('fire_alarm_and_sprinkler', 'Пожарна аларма и спринклери'), ('roofing', 'Покривни работи'), ('insulation', 'Изолация'), ('drywall', 'Гипсокартон'), ('taping', 'Шпакловане'), ('plaster', 'Мазилка'), ('flooring', 'Настилки'), ('finish_carpentry', 'Довършителна дърводелска работа'), ('painting', 'Боядисване'), ('masonry', 'Зидария'), ('landscaping', 'Озеленяване')], max_length=50),
        ),
    ]
