# Generated by Django 5.1.2 on 2024-12-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_specializations_region_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Regions',
        ),
        migrations.RenameModel(
            old_name='Specialization',
            new_name='Specializations',
        ),
    ]
