# Generated by Django 5.1.2 on 2024-11-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_contractorusermodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorusermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contractorusermodel',
            name='last_name',
        ),
    ]
