# Generated by Django 5.1.2 on 2024-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_regularusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_images'),
        ),
    ]
