# Generated by Django 5.1.2 on 2024-11-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_contractorusermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorusermodel',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
