# Generated by Django 5.1.2 on 2024-11-12 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contractorusermodel_email_alter_baseusermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorusermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
