# Generated by Django 5.1.2 on 2024-11-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_contractorusermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorusermodel',
            name='email',
        ),
    ]
