# Generated by Django 5.1.2 on 2024-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_contractorusermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorusermodel',
            name='regions',
            field=models.ManyToManyField(related_name='regions', to='accounts.regions'),
        ),
        migrations.AlterField(
            model_name='contractorusermodel',
            name='specializations',
            field=models.ManyToManyField(related_name='specializations', to='accounts.specializations'),
        ),
    ]
