# Generated by Django 5.1.2 on 2024-11-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_contractorusermodel_regions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorusermodel',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
