# Generated by Django 5.1.2 on 2024-11-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_contractorusermodel_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('min_price_for_similar_project', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price_for_similar_project', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contractor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_project', to='accounts.contractorusermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('contractor_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contractorproject')),
            ],
        ),
    ]
