# Generated by Django 5.1.2 on 2024-11-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_contractorproject_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorproject',
            name='contractor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.contractorusermodel'),
        ),
    ]
