# Generated by Django 5.1.2 on 2024-11-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_contractorproject_contractor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractorproject',
            old_name='name',
            new_name='project_name',
        ),
    ]
