# Generated by Django 5.1.2 on 2024-11-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_name_contractorproject_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractorproject',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='caption',
            new_name='image_caption',
        ),
    ]
