# Generated by Django 5.1.2 on 2024-11-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_imagemodel_contractor_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorproject',
            name='max_price_for_similar_project',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contractorproject',
            name='min_price_for_similar_project',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
