# Generated by Django 5.1.2 on 2024-11-23 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_contractorproject_max_price_for_similar_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractorusermodel',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
