# Generated by Django 5.1.2 on 2024-11-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_contractorusermodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorusermodel',
            name='first_name',
            field=models.CharField(default='defaultname', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractorusermodel',
            name='last_name',
            field=models.CharField(default='defaultlastname', max_length=50),
            preserve_default=False,
        ),
    ]
