# Generated by Django 5.1.2 on 2024-11-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_contractorusermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
