from django.db import models


class UserTypeChoice(models.TextChoices):
    REGULAR_USER = 'regular-user', 'Regular User'
    CONTRACTOR_USER = 'contractor-user', 'Contractor User'


class ContractorRegions(models.TextChoices):
    SOFIA_GRAD = 'Sofia Grad', 'София град'
    PLOVDIV = 'Plovdiv', 'Пловдив'
    VARNA = 'Varna', 'Варна'
    BURGAS = 'Burgas', 'Бургас'
    STARA_ZAGORA = 'Stara Zagora', 'Стара Загора'
    BLAGOEVGRAD = 'Blagoevgrad', 'Благоевград'
    PAZARDZHIK = 'Pazardzhik', 'Пазарджик'
    SOFIA_OBLAST = 'Sofia Oblast', 'София-област'
    PLEVEN = 'Pleven', 'Плевен'
    VELIKO_TARNOVO = 'Veliko Tarnovo', 'Велико Търново'
    HASKOVO = 'Haskovo', 'Хасково'
    RUSE = 'Ruse', 'Русе'
    SLIVEN = 'Sliven', 'Сливен'
    SHUMEN = 'Shumen', 'Шумен'
    DOBRICH = 'Dobrich', 'Добрич'
    KARDJALI = 'Kardzhali', 'Кърджали'
    VRATSA = 'Vratsa', 'Враца'
    MONTANA = 'Montana', 'Монтана'
    LOVEC = 'Lovech', 'Ловеч'
    PERNIK = 'Pernik', 'Перник'
    YAMBOL = 'Yambol', 'Ямбол'
    KYUSTENDIL = 'Kyustendil', 'Кюстендил'
    TARGOVISHTE = 'Targovishte', 'Търговище'
    RAZGRAD = 'Razgrad', 'Разград'
    SILISTRA = 'Silistra', 'Силистра'
    GABROVO = 'Gabrovo', 'Габрово'
    SMOLYAN = 'Smolyan', 'Смолян'
    VIDIN = 'Vidin', 'Видин'

class ContractorSpecializations(models.TextChoices):
    GENERAL_CONTRACTORS = 'general_contractors', 'Главни изпълнители'
    EXCAVATION = 'excavation', 'Изкопни работи'
    CONCRETE = 'concrete', 'Бетон'
    FRAMING = 'framing', 'Рамкиране'
    STEEL = 'steel', 'Стомана'
    WINDOW_AND_DOOR = 'window_and_door', 'Прозорци и врати'
    ELECTRICAL = 'electrical', 'Електрически'
    PLUMBING = 'plumbing', 'ВиК'
    HVAC = 'hvac', 'Отопление, вентилация и климатизация'
    FIRE_ALARM_AND_SPRINKLER = 'fire_alarm_and_sprinkler', 'Пожарна аларма и спринклери'
    ROOFING = 'roofing', 'Покривни работи'
    INSULATION = 'insulation', 'Изолация'
    DRYWALL = 'drywall', 'Гипсокартон'
    TAPING = 'taping', 'Шпакловане'
    PLASTER = 'plaster', 'Мазилка'
    FLOORING = 'flooring', 'Настилки'
    FINISH_CARPENTRY = 'finish_carpentry', 'Довършителна дърводелска работа'
    PAINTING = 'painting', 'Боядисване'
    MASONRY = 'masonry', 'Зидария'
    LANDSCAPING = 'landscaping', 'Озеленяване'