# Generated by Django 5.1.2 on 2024-12-08 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
