# Generated by Django 5.1.2 on 2024-12-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='defaultemail', max_length=100),
            preserve_default=False,
        ),
    ]
