# Generated by Django 5.1.2 on 2024-12-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_email',
        ),
    ]
