# Generated by Django 5.1.2 on 2024-12-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_messages_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, ),
            preserve_default=False,
        ),
    ]
