# Generated by Django 5.1.2 on 2024-12-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_messages_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
